#makefile for project4                                                          


proj_5.x:  myspell.cpp hashtable.hpp
        g++47 -std=c++11 myspell.cpp -o proj_5.x

clean.sh:
        rm *.o *.gch proj5_.x

